# Generated by Django 5.2.6 on 2025-10-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_scheduledcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
