# Generated by Django 5.2.6 on 2025-10-23 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_conversation_metadata_alter_conversation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scheduledcall',
            name='conversation',
        ),
        migrations.AlterModelOptions(
            name='chatbotintent',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='chatbotintent',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='chatbotintent',
            name='requires_auth',
        ),
        migrations.RemoveField(
            model_name='chatbotintent',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='ChatFeedback',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
