# Generated by Django 5.2.6 on 2025-10-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatbotmessage_delete_chatbotintent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read')], default='new', max_length=10),
        ),
    ]
