# Generated by Django 5.2.6 on 2025-10-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_chatbotmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], default='new', max_length=10),
        ),
    ]
