# Generated by Django 5.2.6 on 2025-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminprofile_company_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='admin_role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Project Manager'), ('supervisor', 'Site Supervisor'), ('staff', 'Staff'), ('site_manager', 'Site Manager')], default='staff', max_length=20),
        ),
    ]
