# Generated by Django 5.2.6 on 2025-09-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_adminprofile_admin_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Client Profile', 'verbose_name_plural': 'Client Profiles'},
        ),
    ]
