# Generated by Django 5.2.6 on 2025-10-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_profile_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('client', 'Client'), ('architect', 'Architect')], default='guest', max_length=20),
        ),
    ]
