# Generated by Django 5.2.6 on 2025-10-26 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_update_existing_customer_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePersonnelRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('employee_id_prefix', models.CharField(max_length=2, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Personnel Role',
                'verbose_name_plural': 'Site Personnel Roles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sitemanagerprofile',
            name='site_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='accounts.sitepersonnelrole'),
        ),
    ]
