# Generated by Django 5.2.6 on 2025-10-26 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_sitepersonnelrole_sitemanagerprofile_site_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='architect_gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='accounts.sitemanagerprofile')),
            ],
            options={
                'verbose_name': 'Architect Gallery Image',
                'verbose_name_plural': 'Architect Gallery Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
