# Generated by Django 5.2.6 on 2025-11-17 15:58

import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_architectgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, storage=accounts.storage.AdminProfileStorage(), upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, storage=accounts.storage.ClientProfileStorage(), upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='sitemanagerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, storage=accounts.storage.SiteManagerProfileStorage(), upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='superadminprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, storage=accounts.storage.AdminProfileStorage(), upload_to='profile_pics/'),
        ),
    ]
