# Generated by Django 5.2.6 on 2025-09-24 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('weather_condition', models.CharField(blank=True, choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('stormy', 'Stormy'), ('foggy', 'Foggy'), ('windy', 'Windy'), ('snowy', 'Snowy')], max_length=20)),
                ('temperature_high', models.IntegerField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('temperature_low', models.IntegerField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('humidity', models.IntegerField(blank=True, help_text='Humidity percentage', null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, help_text='Wind speed in km/h', max_digits=5, null=True)),
                ('work_description', models.TextField(help_text='Description of work performed today')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Overall project progress percentage', max_digits=5)),
                ('quality_issues', models.TextField(blank=True, help_text='Any quality issues encountered')),
                ('safety_incidents', models.TextField(blank=True, help_text='Any safety incidents or concerns')),
                ('general_notes', models.TextField(blank=True)),
                ('photos_taken', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DelayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('weather', 'Weather Related'), ('material', 'Material Shortage'), ('equipment', 'Equipment Issues'), ('labor', 'Labor Issues'), ('permit', 'Permit/Approval Delays'), ('design', 'Design Changes'), ('client', 'Client Related'), ('safety', 'Safety Concerns'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=5)),
                ('impact_level', models.CharField(choices=[('low', 'Low Impact'), ('medium', 'Medium Impact'), ('high', 'High Impact'), ('critical', 'Critical Impact')], max_length=10)),
                ('affected_activities', models.TextField(help_text='Which activities were affected')),
                ('mitigation_actions', models.TextField(blank=True, help_text='Actions taken to mitigate the delay')),
                ('responsible_party', models.CharField(blank=True, max_length=100)),
                ('cost_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_entries', to='site_diary.diaryentry')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='diary_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='site_diary.diaryentry')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(help_text='e.g., Excavator, Crane, Mixer', max_length=50)),
                ('operator_name', models.CharField(blank=True, max_length=100)),
                ('hours_operated', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fuel_consumption', models.DecimalField(blank=True, decimal_places=2, help_text='Liters', max_digits=8, null=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Under Maintenance'), ('breakdown', 'Breakdown'), ('idle', 'Idle')], default='operational', max_length=20)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('breakdown_description', models.TextField(blank=True)),
                ('rental_cost_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('work_area', models.CharField(blank=True, max_length=100)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_entries', to='site_diary.diaryentry')),
            ],
        ),
        migrations.CreateModel(
            name='LaborEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_type', models.CharField(choices=[('skilled', 'Skilled Labor'), ('unskilled', 'Unskilled Labor'), ('supervisor', 'Supervisor'), ('engineer', 'Engineer'), ('foreman', 'Foreman'), ('specialist', 'Specialist')], max_length=20)),
                ('trade_description', models.CharField(help_text='e.g., Carpenter, Electrician, Plumber', max_length=100)),
                ('workers_count', models.PositiveIntegerField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('work_area', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='site_diary.diaryentry')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('quantity_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('tons', 'Tons'), ('m3', 'Cubic Meters'), ('m2', 'Square Meters'), ('m', 'Meters'), ('pcs', 'Pieces'), ('bags', 'Bags'), ('liters', 'Liters'), ('rolls', 'Rolls')], max_length=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('quality_check', models.BooleanField(default=True)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_entries', to='site_diary.diaryentry')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='architect_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='site_diary.project'),
        ),
        migrations.CreateModel(
            name='VisitorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('visitor_type', models.CharField(choices=[('client', 'Client'), ('inspector', 'Inspector'), ('consultant', 'Consultant'), ('supplier', 'Supplier'), ('contractor', 'Sub-contractor'), ('official', 'Government Official'), ('other', 'Other')], max_length=20)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('purpose_of_visit', models.TextField()),
                ('areas_visited', models.CharField(blank=True, max_length=200)),
                ('accompanied_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_entries', to='site_diary.diaryentry')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='diaryentry',
            unique_together={('project', 'entry_date')},
        ),
    ]
