# Generated by Django 5.2.6 on 2025-10-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_add_seo_fields'),
        ('site_diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='portfolio_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_diary_projects', to='portfolio.project'),
        ),
    ]
