# Generated by Django 5.2 on 2025-10-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_diary', '0002_project_portfolio_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='portfolio_project',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='draft',
            field=models.BooleanField(default=False, help_text='Save as draft without finalizing entry'),
        ),
    ]
