# Generated by Django 5.2.6 on 2025-10-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_diary', '0003_remove_project_portfolio_project_diaryentry_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
