# Generated by Django 5.2.6 on 2025-10-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_diary', '0006_project_approved_at_project_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('roofing', 'Roofing'), ('flooring', 'Flooring'), ('painting', 'Painting'), ('concrete', 'Concrete'), ('steel', 'Steel Work'), ('carpentry', 'Carpentry'), ('masonry', 'Masonry'), ('landscaping', 'Landscaping'), ('security', 'Security'), ('cleaning', 'Cleaning'), ('other', 'Other')], max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Subcontractor Companies',
                'ordering': ['name'],
            },
        ),
    ]
