# Generated by Django 5.2.6 on 2025-10-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_diary', '0007_subcontractorcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Milestone name (e.g., Foundation Work, Structural Framework)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this milestone phase')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of milestone in project sequence')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this milestone is available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text='Current milestone phase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_diary.milestone'),
        ),
    ]
