# Generated by Django 5.2.6 on 2025-10-21 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_diary', '0008_milestone_diaryentry_milestone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='approval_date',
            new_name='reviewed_date',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='approved',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('needs_revision', 'Needs Revision')], default='complete', max_length=20),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='general_notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='humidity',
            field=models.IntegerField(blank=True, help_text='Humidity percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overall project progress percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='quality_issues',
            field=models.TextField(blank=True, help_text='Any quality issues encountered', max_length=1000),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='safety_incidents',
            field=models.TextField(blank=True, help_text='Any safety incidents or concerns', max_length=1000),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='temperature_high',
            field=models.IntegerField(blank=True, help_text='Temperature in Celsius', null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='temperature_low',
            field=models.IntegerField(blank=True, help_text='Temperature in Celsius', null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='wind_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wind speed in km/h', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='work_description',
            field=models.TextField(help_text='Description of work performed today', max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
