# Generated by Django 5.2.6 on 2025-10-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_diary', '0009_rename_approval_date_diaryentry_reviewed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='needs_revision',
            field=models.BooleanField(default=False),
        ),
    ]
