# Generated by Django 5.2.6 on 2025-10-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_diary', '0010_diaryentry_approval_date_diaryentry_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='approved',
        ),
    ]
