# Generated by Django 5.2.6 on 2025-10-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_diary', '0011_remove_diaryentry_approval_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Worker type name (e.g., Supervisor, Skilled Labor)', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Brief description of this worker type', max_length=200)),
                ('default_daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Default daily rate in PHP', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this worker type is available for selection')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
