# Generated by Django 5.2.6 on 2025-10-22 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_diary', '0012_workertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('work_description', models.TextField()),
                ('daily_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_entries', to='site_diary.diaryentry')),
            ],
        ),
    ]
