# Generated by Django 5.2.6 on 2025-10-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_diary', '0013_subcontractorentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
