# Generated by Django 5.2.6 on 2025-11-17 17:12

import config.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_diary', '0014_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='supervisor_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image data'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.supabase_storage.SupabaseStorage(), upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='Deprecated: Use image field instead', max_length=500, null=True),
        ),
    ]
