# Generated by Django 5.2.6 on 2025-10-02 12:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('keyword', 'Keyword Filter'), ('email_domain', 'Email Domain Filter'), ('ip_address', 'IP Address Filter'), ('length', 'Content Length'), ('links', 'Link Count'), ('caps', 'Excessive Caps')], max_length=20)),
                ('pattern', models.TextField(help_text='Pattern to match (keywords, domains, etc.)')),
                ('action', models.CharField(choices=[('approve', 'Auto Approve'), ('reject', 'Auto Reject'), ('spam', 'Mark as Spam'), ('hold', 'Hold for Review')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment Moderation Rule',
                'verbose_name_plural': 'Comment Moderation Rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_date', models.DateTimeField(blank=True, null=True)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('weekly_digest', models.BooleanField(default=True)),
                ('new_posts', models.BooleanField(default=True)),
                ('featured_posts', models.BooleanField(default=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_opened', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_date'],
            },
        ),
        migrations.AddField(
            model_name='blogimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='blogimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='blogimage',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blogimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='enable_toc',
            field=models.BooleanField(default=True, help_text='Enable table of contents generation'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for featured image (accessibility)', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Image caption', max_length=200),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('author_website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Moderation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('spam', 'Spam')], default='pending', max_length=10)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('spam_score', models.FloatField(default=0.0)),
                ('is_spam', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_like', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='blog.comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Like',
                'verbose_name_plural': 'Comment Likes',
            },
        ),
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('campaign_type', models.CharField(choices=[('weekly_digest', 'Weekly Digest'), ('new_post', 'New Post Notification'), ('featured_post', 'Featured Post'), ('custom', 'Custom Campaign')], default='custom', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('total_opened', models.PositiveIntegerField(default=0)),
                ('total_clicked', models.PositiveIntegerField(default=0)),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Newsletter Campaign',
                'verbose_name_plural': 'Newsletter Campaigns',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('open', 'Email Opened'), ('click', 'Link Clicked'), ('unsubscribe', 'Unsubscribed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.newslettercampaign')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.newslettersubscriber')),
            ],
            options={
                'verbose_name': 'Newsletter Analytics',
                'verbose_name_plural': 'Newsletter Analytics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['blog_post', 'status', 'created_at'], name='blog_commen_blog_po_8fc798_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['status', 'created_at'], name='blog_commen_status_399a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='blog_commen_parent__43ce68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment', 'user', 'ip_address')},
        ),
    ]
