# Generated by Django 5.2.6 on 2025-10-02 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commentmoderationrule_newslettersubscriber_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When this post was rejected', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Admin who rejected this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text="Admin's reason for rejection", null=True),
        ),
    ]
