# Generated by Django 5.2.6 on 2025-10-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_rejected_at_blogpost_rejected_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_email',
            field=models.EmailField(max_length=254),
        ),
    ]
