# Generated by Django 5.2.6 on 2025-10-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
