# Generated by Django 5.2.6 on 2025-10-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='newsletter_sent',
            field=models.BooleanField(default=False, help_text='Newsletter has been sent'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='send_newsletter',
            field=models.BooleanField(default=False, help_text='Send newsletter when published'),
        ),
    ]
