# Generated by Django 5.2.6 on 2025-11-15 13:05

import blog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_newsletter_sent_blogpost_send_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(storage=blog.storage.BlogSupabaseStorage(), upload_to='blog/gallery/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main image for the blog post', null=True, storage=blog.storage.BlogSupabaseStorage(), upload_to='blog/featured_images/'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='image',
            field=models.ImageField(storage=blog.storage.BlogSupabaseStorage(), upload_to='blog/content/'),
        ),
    ]
