"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # If python-dotenv is not installed, continue without it
    pass

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-=n3t-sn4a)i%$30f*!y^7t3pq(g#*v6@0gkzluw)ejol8oi*-z')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Parse ALLOWED_HOSTS from environment variable
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',')]
if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(os.environ.get('RENDER_EXTERNAL_HOSTNAME'))
if os.environ.get('RAILWAY_PUBLIC_DOMAIN'):
    ALLOWED_HOSTS.append(os.environ.get('RAILWAY_PUBLIC_DOMAIN'))

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom apps
    'core',
    'accounts',
    'portfolio',
    'site_diary',
    'blog',
    'chatbot',
    'admin_side',
    # Third-party apps
    'axes',
    'storages',
    'csp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
] + (['csp.middleware.CSPMiddleware'] if not DEBUG else []) + [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.online_middleware.OnlineStatusMiddleware',  # Track user online status
    'core.middleware.UnauthorizedAccessMiddleware',  # Custom 401 error handling - BEFORE messages
    'django.contrib.messages.middleware.MessageMiddleware',
    'accounts.middleware.RoleBasedAccessMiddleware',  # Role-based access control
    'admin_side.middleware.AdminAuthenticationMiddleware',  # Admin authentication control
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # Shared templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.role_context',  # Role-based context
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database configuration
import dj_database_url

if os.getenv('DATABASE_URL'):
    # PostgreSQL - Using DATABASE_URL (recommended)
    DATABASES = {
        'default': dj_database_url.parse(os.getenv('DATABASE_URL'))
    }
    # Ensure connection settings for PostgreSQL
    DATABASES['default']['CONN_MAX_AGE'] = 0  # Close connections immediately
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'require',
        'connect_timeout': 10,
    }
else:
    # PostgreSQL - Using individual environment variables (fallback)
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DB_NAME', 'tripleg_db'),
            'USER': os.getenv('DB_USER', 'tripleg_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'd8GpSfe5Tb5uNSPvjosneUe9h8MSLXHz'),
            'HOST': os.getenv('DB_HOST', 'dpg-d3r8hqu3jp1c7394km30-a.singapore-postgres.render.com'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Email settings for Gmail
# Email settings - Use environment variables
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'triplegotp@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'wzukyxhnuomdglir')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '30'))
EMAIL_SSL_CERTFILE = os.getenv('EMAIL_SSL_CERTFILE', None)
EMAIL_SSL_KEYFILE = os.getenv('EMAIL_SSL_KEYFILE', None)
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER', 'triplegotp@gmail.com')

# SSL Configuration for email
if os.getenv('EMAIL_SSL_CHECK_HOSTNAME', 'True').lower() == 'false':
    import ssl
    # Create unverified SSL context for development
    EMAIL_SSL_CONTEXT = ssl.create_default_context()
    EMAIL_SSL_CONTEXT.check_hostname = False
    EMAIL_SSL_CONTEXT.verify_mode = ssl.CERT_NONE

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Use different static file storage based on environment
if DEBUG:
    # Development - use default storage
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    # Production - use whitenoise with compression
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Supabase Storage Configuration
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_KEY = os.getenv('SUPABASE_KEY')
SUPABASE_BUCKET = os.getenv('SUPABASE_BUCKET', 'project-images')
SUPABASE_PORTFOLIO_BUCKET = 'portfolio_project_images'
SUPABASE_BLOG_BUCKET = 'blog_images'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Render.com Media Configuration
USE_RENDER_STATIC = os.getenv('USE_RENDER_STATIC', 'False').lower() == 'true'

# Enhanced Media Configuration for Render
if USE_RENDER_STATIC and not DEBUG:
    # Production on Render - serve all media as static files
    MEDIA_URL = '/static/media/'
    MEDIA_ROOT = BASE_DIR / 'static' / 'media'
    
    # Ensure all media directories are collected
    STATICFILES_DIRS = [
        BASE_DIR / "static",
        BASE_DIR / "static/media",
        BASE_DIR / "static/media/videos",
        BASE_DIR / "static/media/profile_pics",
        BASE_DIR / "static/media/projects",
    ]
else:
    # Local development storage
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    STATICFILES_DIRS = [BASE_DIR / "static"]

# Login/logout URLs
LOGIN_URL = '/accounts/sitemanager/login/'
LOGIN_REDIRECT_URL = '/admin-panel/'

# Site URL for newsletter and email links
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')

# Security settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Weather API Configuration
WEATHER_API_KEY = os.getenv('WEATHER_API_KEY', 'your_openweathermap_api_key_here')
WEATHER_API_URL = 'https://api.openweathermap.org/data/2.5/weather'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Axes Security Configuration
AXES_FAILURE_LIMIT = 5  # lock out after 5 attempts
AXES_COOLOFF_TIME = 1  # lockout period in hours
AXES_LOCKOUT_TEMPLATE = 'client/lockout.html'  # create a lockout page

# Axes lockout configuration (updated for django-axes 5.0+)
AXES_LOCK_OUT_AT_FAILURE = True
AXES_RESET_ON_SUCCESS = True

# Cache configuration for online status tracking
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutes
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Content Security Policy (django-csp 4.0+ format)
if DEBUG:
    # Development - Disable CSP for easier weather API testing
    CONTENT_SECURITY_POLICY = {'DIRECTIVES': {}}
else:
    # Production - Enable CSP with weather API allowances
    CONTENT_SECURITY_POLICY = {
        'DIRECTIVES': {
            'base-uri': ["'self'"],
            'connect-src': ["'self'", 'https://cdn.jsdelivr.net', 'https://maps.googleapis.com', 'https://nominatim.openstreetmap.org', 'https://api.openweathermap.org', 'http://api.openweathermap.org'],
            'default-src': ["'self'"],
            'font-src': ["'self'", 'https://fonts.gstatic.com', 'https://cdnjs.cloudflare.com'],
            'form-action': ["'self'"],
            'frame-src': ['https://www.google.com', 'https://maps.google.com'],
            'img-src': ["'self'", 'data:', 'https:', 'http:'],
            'object-src': ["'none'"],
            'script-src': ["'self'", "'unsafe-inline'", 'https://cdn.jsdelivr.net', 'https://cdnjs.cloudflare.com', 'https://code.jquery.com', 'https://maps.googleapis.com', 'https://unpkg.com'],
            'style-src': ["'self'", "'unsafe-inline'", 'https://fonts.googleapis.com', 'https://cdn.jsdelivr.net', 'https://cdnjs.cloudflare.com', 'https://unpkg.com']
        }
    }