"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # If python-dotenv is not installed, continue without it
    pass

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-=n3t-sn4a)i%$30f*!y^7t3pq(g#*v6@0gkzluw)ejol8oi*-z')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Parse ALLOWED_HOSTS from environment variable
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',')]
if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(os.environ.get('RENDER_EXTERNAL_HOSTNAME'))

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom apps
    'core',
    'accounts',
    'portfolio',
    'site_diary',
    'blog',
    'chatbot',
    'admin_side',
    # Third-party apps
    'axes',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.UnauthorizedAccessMiddleware',  # Custom 401 error handling - BEFORE messages
    'django.contrib.messages.middleware.MessageMiddleware',
    'accounts.middleware.RoleBasedAccessMiddleware',  # Role-based access control
    'admin_side.middleware.AdminAuthenticationMiddleware',  # Admin authentication control
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # Shared templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.role_context',  # Role-based context
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'tripleg_postgre_sql'),
        'USER': os.getenv('DB_USER', 'tripleg_postgre_sql_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'r4bKPWIPB9toQ8awybGsEtjg74YTG33X'),
        'HOST': os.getenv('DB_HOST', 'dpg-d375ipur433s73eecc10-a.singapore-postgres.render.com'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Email settings for Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'triplegotp@gmail.com'  # Replace with your Gmail address
EMAIL_HOST_PASSWORD = 'wzukyxhnuomdglir'  # Gmail App Password, no spaces
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'triplegotp@gmail.com'

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Render.com Media Configuration
USE_RENDER_STATIC = os.getenv('USE_RENDER_STATIC', 'False').lower() == 'true'

# Enhanced Media Configuration for Render
if USE_RENDER_STATIC and not DEBUG:
    # Production on Render - serve all media as static files
    MEDIA_URL = '/static/media/'
    MEDIA_ROOT = BASE_DIR / 'static' / 'media'
    
    # Ensure all media directories are collected
    STATICFILES_DIRS = [
        BASE_DIR / "static",
        BASE_DIR / "static/media",
        BASE_DIR / "static/media/videos",
        BASE_DIR / "static/media/profile_pics",
        BASE_DIR / "static/media/projects",
    ]
else:
    # Local development storage
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    STATICFILES_DIRS = [BASE_DIR / "static"]

# Login/logout URLs
LOGIN_URL = '/accounts/sitemanager/login/'
LOGIN_REDIRECT_URL = '/admin-panel/'

# Security settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AXES_FAILURE_LIMIT = 5  # lock out after 5 attempts
AXES_COOLOFF_TIME = 1  # lockout period in hours
AXES_LOCKOUT_TEMPLATE = 'client/lockout.html'  # create a lockout page

# Optional: lockout by username and IP
AXES_ONLY_USER_FAILURES = False
AXES_LOCK_OUT_AT_FAILURE = True
AXES_RESET_ON_SUCCESS = True