# Generated by Django 5.2.6 on 2025-09-23 19:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)])),
                ('location', models.CharField(max_length=255)),
                ('size', models.CharField(help_text='e.g., 350 m², 2500 sq ft', max_length=50)),
                ('duration', models.CharField(help_text='e.g., 14 Months, 2 Years', max_length=50)),
                ('completion_date', models.DateField()),
                ('lead_architect', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Show in featured projects section')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='projects/hero/')),
                ('video', models.FileField(blank=True, null=True, upload_to='projects/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.category')),
            ],
            options={
                'ordering': ['-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('alt_text', models.CharField(help_text='Descriptive text for accessibility', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in gallery')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in timeline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g., 'Total Area', 'Floors', 'Rooms'", max_length=100)),
                ('value', models.CharField(help_text="e.g., '350 m²', '3', '5 Bedrooms'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('project', 'label')},
            },
        ),
    ]
