# Generated by Django 5.2.6 on 2025-10-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hero_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for hero image (accessibility)', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (max 160 chars). Leave blank to auto-generate from description.', max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_meta_title',
            field=models.CharField(blank=True, help_text='SEO optimized title (max 60 chars). Leave blank to use project title.', max_length=60),
        ),
    ]
