# Generated by Django 5.2.6 on 2025-11-15 11:51

import portfolio.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectupdaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='publish_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, storage=portfolio.storage.PortfolioSupabaseStorage(), upload_to='projects/hero/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, storage=portfolio.storage.PortfolioSupabaseStorage(), upload_to='projects/videos/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(storage=portfolio.storage.PortfolioSupabaseStorage(), upload_to='projects/gallery/'),
        ),
    ]
